{{- if .Values.configInline }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hcloud-fip-controller.configMapName" . }}
  labels:
{{ include "hcloud-fip-controller.labels" . | nindent 4 }}
data:
  config.json: |
{{ toJson .Values.configInline | indent 4 }}
{{- end }}
