{{- if .Values.secretInline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcloud-fip-controller.envSecretName" . }}
  labels:
{{ include "hcloud-fip-controller.labels" . | nindent 4 }}
stringData:
{{ .Values.secretInline | indent 2 }}
{{- end }}
